# Generated by Django 4.2.6 on 2023-10-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True, verbose_name='название сервиса')),
                ('password', models.CharField(max_length=255, verbose_name='пароль')),
            ],
            options={
                'verbose_name': 'данные',
                'verbose_name_plural': 'данные',
            },
        ),
    ]
